-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHASE_USERS, ROUND((COUNT(DISTINCT A.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%')), 1) AS PURCHASED_RATIO
FROM USER_INFO AS A
JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID WHERE A.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR(B.SALES_DATE) ASC, MONTH(B.SALES_DATE) ASC;