-- 코드를 입력하세요
SELECT PRODUCT_CODE, (A.PRICE * SUM(B.SALES_AMOUNT)) AS SALES
FROM PRODUCT AS A
JOIN OFFLINE_SALE AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;